language: java
jdk:
  - openjdk8
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "app/target/app-1.0.0.5-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    branch: travis-test
